apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
  labels:
    app: echo
spec:
  type: ClusterIP
  ports:
  - port: 30000
    targetPort: 30000
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: echo
    spec:
      serviceAccountName: echo
      containers:
      - name: echo
        image: narate/tcpbin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30000
